config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts do
    resources :comments
  end
  devise_for :users
  # get 'posts#about', as: 'about'
  get 'about', action: :about, controller: 'posts'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  #belongs_to :category
  validates :category, presence: true;
  validates :title, :subtitle, :body, presence: true, length: { minimum: 5 }
  scope :ordered, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def username
    return self.email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    #@comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index, :about]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.ordered
    @cat = Category.all
  end

  def show
  end

  def about 
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :subtitle, :body, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_alerts.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"> <%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="page-footer bg-warning p-2" id="footer">
  <div class="container-fluid">
    <div class="row text-center p-3">
      <div class="col sm-12">
        <!-- Facebook -->
        <a class="fb-ic" href="https://www.facebook.com/profile.php?id=100009082774096">
          <i class="fa fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"></i>
        </a>
        <!-- Telegram -->
        <a class="tw-ic" href="https://t.me/Mr_Andrii_H">
          <i class="fa fa-telegram fa-lg white-text mr-md-5 mr-3 fa-2x"></i>
        </a>
        <!--Instagram-->
        <a class="ins-ic" href="https://www.instagram.com">
          <i class="fa fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"></i>
        </a>
      </div>
    </div>
    <!-- Copyright -->
    <div class="footer-copyright text-center pb-2">
      <span>© 2020 Copyright: <a href="https://simpledevblog.herokuapp.com/">Simpleblog</a></span>
    </div>
  </div>



</footer>

app/views/layouts/_nav.html.erb
<nav class = "navbar navbar-expand-md bg-warning navbar-light" id="navigationbar">
<div class="container">
  <span class = "navbar-link navbar-brand">
    <h2><%= link_to 'Simple blog', posts_path, class: "text-dark font-weight-bold"%></h2>
  </span>
  <button class="navbar-toggler" type = "button" data-toggle="collapse" data-target="#navdata">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id = "navdata">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to 'Про нас', about_path, class: 'btn text-center text-muted', id: 'link' %>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Додати пост', new_post_path, class: 'btn text-center', id: 'link'%>	&nbsp;
        </li>
      <% end %>
      <li class="nav-item">
        <% if !current_user %>
          <%= link_to 'Вхід', new_user_session_path, class: "btn text-center" , id: 'link'%>
        <% else %>
          <%= link_to 'Вихід', destroy_user_session_path, method: :delete, class: "btn text-center", id: 'link' %>
        <%end %>
      </li>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'layouts/nav' %>
      <%= render 'layouts/alerts' %>
      <div class="container-fluid">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="container">
      <h2> Помилок: <%= post.errors.count %>  при спробі зберегти пост:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <div class="form-group">
      <%= form.label 'Заголовок' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label 'Підзаголовок' %>
      <%= form.text_field :subtitle, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label 'Тіло поста' %>
      <%= form.text_area :body, class: 'form-control' %>
    </div>
    <div class="form-group w-100">
      <%= form.label "Категорія" %>
      <%= form.collection_select(:category, Category.all, :id, :name, class: "form-control form-control-lg", multiple: false) %>
    </div>
    <div class="form-submit">
      <%= form.submit('Зберегти',class:'btn btn-success w-100') %>
    </div>
    </div>
<% end %>

app/views/posts/about.html.erb
<div class="container">
 <h2 class="w-100 text-center">Про нас</h2>
  <p class="text-justify">
    Цей блог був розроблений під час навчального процесу і призначений для вивчення мови програмування
    Ruby. отриманий досвід буде дуже корисним мені в майбутньому.
    <br/>
    Для отримання отримання інформації щодо сайту або повідомлення про помилки зверніться до адміністратора (телеграм @Mr_Andrii_H)
  </p>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="text-center">Редагування поста</h1>
  <%= render 'form', post: @post %>
<div class="container text-center p-2">
  <%= link_to 'Показати пост', @post, class: "btn btn-secondary" %> |
  <%= link_to 'Назад', posts_path, class: "btn btn-primary" %>
</div>

</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="container">
      <div id = "post-header">
          <h2 ><%= post.title %> | <span class="text-muted " id="category"><%= @cat[post.category.to_i-1].name%></span></h2>
      </div>
      <div>
        <h4 class="text-muted text-left"><%=  post.subtitle %></h4>
      </div>
      <div class="row">
          <div class="col-md-6 text-left">
            <p class="text-muted"> Написав: 	&nbsp;	<%=  post.user.username %></p>
          </div>
          <div class="col md-6 text-right">
            <p class="text-muted">В:&nbsp; <%=  post.created_at %></p>
          </div>
      </div>
      <div>
        <%= link_to 'Читати', post, class: "btn btn-primary" %>
        <% if current_user && current_user.admin %>
          <%= link_to 'Редагувати', edit_post_path(post), class: "btn btn-secondary" %>
          <%= link_to 'Видалити', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <%end %>
      </div>
    </div>
  <hr>
<%end %>
<br />

app/views/posts/new.html.erb
<div class="container">
  <h1 class="text-center w-100">Новий пост</h1>
  <%= render 'form', post: @post %>
<div id ="cansel">
  <%= link_to 'Скасувати', posts_path, class: 'btn btn-danger text-center w-100 p-2'  %><br/>
</div>


</div>

app/views/posts/show.html.erb
 <div class = 'container'>
    <div class="text-center">
      <h1><%= @post.title %></h1>
    </div>
    <div>
      <h3><%= @post.subtitle %></h3>
    </div>
    <div>
      <p><%= @post.body %></p>
    </div>
    <div class="text-muted">
      <div class="row">
        <div class="col-md-6 text-left">
          <p>Написав:&nbsp;<%= @post.user.username %></p>
        </div>
        <div class="col-md-6 text-right">
          <p>В: <%= @post.created_at %></p>
        </div>
      </div>
    </div>
  </div>
  <div class=" container">
    <% if current_user %>
      <% if current_user == @post.user || current_user.admin %>
        <%= link_to 'Редагувати', edit_post_path(@post), {:class => 'btn btn-secondary'}%> |
        <%= link_to 'Видалити', post_path(@post), method: :delete,data: { confirm: 'Are you sure?'} , class: 'btn btn-danger' %> | <!---->
      <% end %>
    <% end %>
    <%= link_to 'Назад', posts_path, {:class => 'btn btn-primary'} %>
  </div>
 <hr>
 <div class=" container">
 <h3>Коментарі</h3>
<% @post.comments.each do |comment| %>

    <div class="row">
      <strong><%= comment.user.username%></strong>
       &nbsp&nbsp&nbsp&nbsp
      <% if current_user %>
      <%if comment.user == current_user || current_user.admin %>
          <%= link_to 'detete', [comment.post, comment],method: :delete, data: { confirm: 'Are you sure?'} %>
      <% end %>
        <%end %>
      <br />
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-8 text-muted text-left">
        <%= comment.body %>
      </div>
      <div class="col-sm-12 col-md-4 text-muted text-right">
        <%=comment.created_at %>
      </div>
    </div>

    <br />
<% end %>
 </div>
<hr>

<div class="form container">
  <%if current_user %>
    <h5>Додати коментар</h5>
  <%= form_for ([@post, @post.comments.build]) do |f|  %>
    <div class="form-group">
      <%= f.text_area(:body, class:"form-control", placeholder: 'Текст коментаря' )  %>
    </div>
    <div class="form-group">
      <%= f.submit("Додати коментар",class: "btn btn-warning mb-3") %>
    </div>
  <% end %>
    <% else %>
      <h6 class="text-muted"><%= 'Увійдіть щоб залишити кометар' %></h6>
    <% end %>
</div>